---
# tasks file for terraform
- name: create directory for terraform
  file:
    path: '{{ terraform_binary_dir }}'
    state: directory
    mode: 0755
- name: download terraform...
  get_url:
    url: '{{ terraform_url }}'
    dest: '{{ terraform_install_dir }}'
    mode: 0644
- name: unarchive terraform...
  unarchive:
    remote_src: yes
    src: '{{ terraform_install_dir }}/terraform_0.12.7_linux_amd64.zip'
    dest: '{{ terraform_install_dir }}'